name: Deploy to GitHub Pages

on:
  release:
    types: [published] 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Подготовка версионной папки
        run: |
          mkdir -p v${{ github.event.release.tag_name }}
          cp -r $(ls -A | grep -v "^v${{ github.event.release.tag_name }}$" | grep -v "^.git$" | grep -v "^.github$") v${{ github.event.release.tag_name }}/

      - name: Деплой на GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./v${{ github.event.release.tag_name }}
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
