name: Deploy Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages-dir

      - name: Prepare versioned folder
        run: |
          VERSION="${{ github.ref_name }}"
          VERSION="${VERSION#v}"
          
          # Создаем версионную папку в gh-pages
          mkdir -p gh-pages-dir/v$VERSION
          
          # Копируем файлы из текущей рабочей директории (main) в версионную папку
          cp -r ./en ./ru ./index.html gh-pages-dir/v$VERSION/

      - name: Deploy to gh-pages
        run: |
          cd gh-pages-dir
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy version ${{ github.ref_name }}"
          git push
