name: Deploy Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main-source

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages-target

      - name: Prepare versioned folder
        run: |
          VERSION="${{ github.ref_name }}"
          VERSION="${VERSION#v}"
          
          # Создаем версионную папку в gh-pages
          mkdir -p gh-pages-target/v$VERSION
          
          # Копируем файлы из main branch в версионную папку
          cp -r main-source/ru main-source/en main-source/index.html gh-pages-target/v$VERSION/

      - name: Deploy to gh-pages
        run: |
          cd gh-pages-target
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy version ${{ github.ref_name }}"
          git push
